// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 711 06/05/2020)
// Created on Fri May 21 15:35:16 2021

branch_controller branch_controller_inst
(
	.instr_exe_4(instr_exe_4_sig) ,	// input [3:0] instr_exe_4_sig
	.instr_decode_4(instr_decode_4_sig) ,	// input [3:0] instr_decode_4_sig
	.alu_out(alu_out_sig) ,	// input [15:0] alu_out_sig
	.mno(mno_sig) 	// output [2:0] mno_sig
);

